name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - yeenbean
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Be clear and concise.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you thought you'd see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge (Chromium)
        - Other (write below)
    validations:
      required: true
  - type: input
    id: other-browser
    attributes:
      label: Other browser?
      description: Only required if you selected "Other" above.
      placeholder: Vivaldi
    validations:
      required: false
  - type: textarea
    id: addl-info
    attributes:
      label: Anything else we should know?
      description: You can include log output, nuances to your experience, and anything else.
    validations:
      required: false
